from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ExpenseViewSet

# Create a router and register the ExpenseViewSet
# This automatically generates all CRUD routes
# as well as custom @action endpoints
router = DefaultRouter()
router.register(r'expenses', ExpenseViewSet, basename='expense')

# Include all routes generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
